language: node_js
node_js:
  - "10"

after success:
  - npm run coverage

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - SECRET=love
